# catch

允许函数捕获运行时异常。并从异常发生处之后恢复函数执行。详见[异常处理]()。

>`catch`属性只能单独使用。